# Generated by Django 3.1.4 on 2020-12-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201204_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='starts',
            new_name='stars',
        ),
    ]
